AWSTemplateFormatVersion: "2010-09-09"

Description: Deploys Lambda to handle latest AMI search function

Parameters:
    LambdaBucket:
        Type: String
    ZipName:
        Type: String
    LambdaName:
        Type: String

Resources:
    lambdaiam:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub "${LambdaName}-iam"
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -
                        Effect: Allow
                        Principal:
                            Service:
                                - lambda.amazonaws.com
                        Action:
                            - sts:AssumeRole
            Path: "/"
            Policies:
                -
                    PolicyName: policy
                    PolicyDocument:
                        Version: 2012-10-17
                        Statement:
                            -
                                Effect: Allow
                                Action:
                                    - logs:*
                                Resource:
                                    - arn:aws:logs:*:*:*
                            -
                                Effect: Allow
                                Action:
                                    - ec2:Describe*
                                Resource:
                                    - "*"
    lambdafunction:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: !Ref LambdaName
            Handler: ami_search.lambda_handler
            Role:
                Fn::Join:
                    - ""
                    -
                        - "arn:aws:iam::"
                        - !Ref AWS::AccountId
                        - ":role/"
                        - !Ref lambdaiam
            Code:
                S3Bucket: !Ref LambdaBucket
                S3Key: !Ref ZipName
            Runtime: python3.11
            Timeout: 25
Outputs:
    LambdaFunction:
        Description: LambdaFunction
        Value: !Ref lambdafunction
